version: '3.9'
services:
  eraporsmk:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eraporsmk_container
    user: www-data
    restart: always
    networks:
      - erapor-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_TIMEZONE=Asia/Jakarta
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_container
      - DB_PORT=5432
      - DB_DATABASE=eraporsmk
      - DB_USERNAME=eraporsmk
      - DB_PASSWORD=eraporsmk

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/eraporsmk
    depends_on:
      - eraporsmk
    networks:
      - erapor-network
    command: [ "/bin/sh", "-c", "nginx -g 'daemon off;'" ]

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=eraporsmk
    networks:
      - erapor-network

  database:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: eraporsmk
      POSTGRES_PASSWORD: eraporsmk
      POSTGRES_DB: eraporsmk
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - erapor-network
    restart: unless-stopped

networks:
  erapor-network:


volumes:
  postgres_data:
  redis_data:
    driver: local
