version: '3.9'
services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: erapor_app_webserver
    ports:
      - "8030:80"
    depends_on:
      - database
    networks:
      - erapor
    restart: always
  
  redis:
    image: redis:alpine
    container_name: erapor_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=eraporsmk
    networks:
      - erapor

  database:
    image: postgres:17
    container_name: erapor_database
    environment:
      POSTGRES_USER: postgres      # Username untuk PostgreSQL
      POSTGRES_PASSWORD: eraporsmk # Password untuk user
      POSTGRES_DB: eraporsmk       # Nama database yang dibuat saat startup
    ports:
      - "5432:5432"                # Port PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erapor
    restart: unless-stopped

networks:
  erapor:

volumes:
  postgres_data:
  redis_data:
    driver: local